#!/bin/sh /etc/rc.common

START=98
USE_PROCD=1

start_service()
{
	procd_open_instance

	procd_set_param env LUMIMQTT_CONFIG=/etc/lumimqtt.json
	procd_set_param command lumimqtt
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
